# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GCNZI9T1o5Kd2YaI0tIzM62gO1l0wx-U
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install numpy
# %pip install matplotlib
# %pip install librosa
# %pip install pandas

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import librosa

D = librosa.stft(y)  # STFT of y
S_db = librosa.amplitude_to_db(np.abs(D), ref=np.max)

fig, ax = plt.subplots()
img = librosa.display.specshow(S_db, ax=ax)
fig.colorbar(img, ax=ax)

y, sr = librosa.load('Colorful-Flowerschosic.com.mp3')

y, sr = librosa.load('/content/Дворы (320kbps).mp3')

y, sr = librosa.load('Rammstein - Sonne (Official Video) (320kbps).mp3')

y, sr = librosa.load('/content/FIFTY FIFTY - Cupid (Sped Up) (Twin Version) (Lyrics) (320kbps).mp3')

tempo, beat_frames = librosa.beat.beat_track(y=y, sr=sr)

tempo

tempo

#alltempos = [1,2,3,4]
data = pd.DataFrame({'tempoes': [1,2,3,4]})

data.head()

beat_frames

beat_frames

sum = 0
for i in range(len(beat_frames) - 1):
  sum += beat_frames[i+1] - beat_frames[i]

avg = sum / len(beat_frames)

avg